name: card_list_swipe
description: "A Flutter package that provides a horizontally scrollable stack of dismissible cards with rolling animation effects, perfect for mailbox-style interfaces."
version: 0.0.1
homepage: https://github.com/ekakshjanweja/card_list_swipe

environment:
  sdk: ^3.0.0
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.ekakshjanweja.card_list_swipe
        pluginClass: CardListSwipePlugin
      ios:
        pluginClass: CardListSwipePlugin
      macos:
        pluginClass: CardListSwipePlugin
      linux:
        pluginClass: CardListSwipePlugin
      windows:
        pluginClass: CardListSwipePlugin
      web:
        pluginClass: CardListSwipePlugin
      fuchsia:
        pluginClass: CardListSwipePlugin
